name: CI

on: [pull_request, push, workflow_dispatch]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Shell Check
      run: ./shellcheck.sh
      shell: bash

  build:
    name: Build
    needs: check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - target: x86_64-unknown-linux-gnu
          arch: x86_64
          os: ubuntu-22.04
          ninja_file: ninja-linux.zip
          ninja_dir: /usr/local/bin
          ninja_sudo: sudo
          rust: stable
          tar: linux
          out_dir: out
        - target: aarch64-unknown-linux-gnu
          arch: aarch64
          os: ubuntu-22.04-arm
          ninja_file: ninja-linux-aarch64.zip
          ninja_dir: /usr/local/bin
          ninja_sudo: sudo
          rust: stable
          tar: linux
          out_dir: out
        - target: aarch64-apple-darwin
          arch: aarch64
          os: macos-latest
          ninja_file: ninja-mac.zip
          ninja_dir: /usr/local/bin
          ninja_sudo: sudo
          rust: stable
          tar: osx
          out_dir: out
        - target: x86_64-apple-darwin
          arch: x86_64
          os: macos-13
          ninja_file: ninja-mac.zip
          ninja_dir: /usr/local/bin
          ninja_sudo: sudo
          rust: stable
          tar: osx
          out_dir: out
        - target: x86_64-pc-windows-msvc
          arch: x86_64
          os: windows-latest
          ninja_file: ninja-win.zip
          ninja_dir: /usr/bin
          ninja_sudo:
          rust: stable
          tar: windows
          out_dir: /c/out
    steps:
    - uses: actions/checkout@v4
    - name: Install coreutils and swig
      run: |
        brew update && brew install coreutils swig ninja
      if: matrix.tar == 'osx'
      shell: bash
    - name: Install Linux tools for LLDB
      run: |
        sudo apt-get install build-essential swig python3-dev libedit-dev libncurses5-dev libxml2-dev
      if: matrix.os == 'ubuntu-22.04'
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      if: matrix.os == 'ubuntu-22.04'
      with:
        tool-cache: false
    - name: Install Ninja
      run: |
        curl -L -O "https://github.com/ninja-build/ninja/releases/download/v1.12.1/${{ matrix.ninja_file }}" && \
        ${{ matrix.ninja_sudo }} unzip -o ${{ matrix.ninja_file }} -d ${{ matrix.ninja_dir }} && rm ${{ matrix.ninja_file }}
      if: matrix.tar != 'osx'
      shell: bash
    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: 1.89.0
    - name: Build
      run: ./build.sh ${{ matrix.out_dir }}
      shell: bash
    - name: Upload ${{ matrix.tar }} tarball
      uses: actions/upload-artifact@v4
      with:
        name: platform-tools-${{ matrix.tar }}-${{ matrix.arch }}.tar.bz2
        path: platform-tools-${{ matrix.tar }}-${{ matrix.arch }}.tar.bz2

  release:
    name: Upload Release Assets
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    steps:
    - name: Download Linux x86 tarball
      uses: actions/download-artifact@v4
      with:
        name: platform-tools-linux-x86_64.tar.bz2
    - name: Download Linux ARM tarball
      uses: actions/download-artifact@v4
      with:
        name: platform-tools-linux-aarch64.tar.bz2
    - name: Download macOS ARM tarball
      uses: actions/download-artifact@v4
      with:
        name: platform-tools-osx-aarch64.tar.bz2
    - name: Download macOS x86 tarball
      uses: actions/download-artifact@v4
      with:
        name: platform-tools-osx-x86_64.tar.bz2
    - name: Download Windows tarball
      uses: actions/download-artifact@v4
      with:
        name: platform-tools-windows-x86_64.tar.bz2
    - name: Generate SHA256SUMS
      run: sha256sum platform-tools-*.tar.bz2 > SHA256SUMS
      shell: bash
    - name: Create Release and Upload Assets
      uses: softprops/action-gh-release@v2
      with:
        name: Trezoa platform-tools ${{ github.ref_name }}
        files: |
          platform-tools-linux-x86_64.tar.bz2
          platform-tools-linux-aarch64.tar.bz2
          platform-tools-osx-aarch64.tar.bz2
          platform-tools-osx-x86_64.tar.bz2
          platform-tools-windows-x86_64.tar.bz2
          SHA256SUMS
